"Raihan's vim config

syntax on
set nu rnu
set smartcase
set smartindent
set smarttab
set expandtab
set cindent
set tabstop=2
set shiftwidth=2
set encoding=UTF-8
set clipboard+=unnamedplus
filetype plugin indent on

set termguicolors

nnoremap <S-k> gt
nnoremap <S-j> gT

" //search
nnoremap <silent> <C-L> :nohlsearch<CR><C-L>
