#!/bin/bash

# variable ?
nginxdir=$(eval echo '/usr/share/nginx/html')
nvimdir=$(eval echo '/home/$(whoami)/.config/nvim')


# doing something
alias pls='sudo $(fc -ln -1)'
alias open="xdg-open"
alias c="clear"
alias q="exit"
alias man="man -P \"sh -c 'col -b | nvim -c \\\"set ft=man nomod nolist\\\" -'\""
alias nnn='nnn -de'
alias sizedir="du -h --max-depth=1"

# edit config
alias zshalias="vi ~/.zsh_aliases"
alias zshplugin="vi ~/.dotfiles/dots/zsh_plugins"
alias zshconfig="vi ~/.zshrc"
alias vimconfig="vi ~/.vimrc"
alias nvimconfig="vi ~/.config/nvim/init.lua"

# replace with better app // admin
alias vi="nvim" # neovim
alias isw="sudo isw" # ice sealead wyvern on github
alias pomo="spt -e 'aplay $HOME/Music/alarm.wav'" # suckless' spt

# directories
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ls='ls --color=auto'
alias la='ls -la --color=auto'
alias l='ls -d .* --color=auto'
alias lsimg=$'for f (*.(jpeg|jpg|gif|png)) {printf $f;php -r "print_r(getimagesize(\'$f\'));" |grep -w width |sed \'s/ .3] =>//\'}'

alias nginxdir='cd /usr/share/nginx/html'
alias nvimdir='cd ~/.config/nvim'

# mount android
alias androidmount='aft-mtp-mount $HOME/MountHere' # mount android, android-file-transfer on pacman
alias androidumount='umount $HOME/MountHere' # same as above, but unmount it

# network
alias wifi='nmtui'

# optimus manager
alias om="optimus-manager"
alias omswitch="optimus-manager --switch"
alias omstatus="optimus-manager --status"
alias omhybrid="optimus-manager --switch hybrid && killmyself"
alias omnvidia="optimus-manager --switch nvidia && killmyself"

# kill all session
alias killmyself="pkill -KILL -u $USER"

# some fancy stuff that i rarely use
alias lyrics="sptlrx" # sptlrx-bin

# record (use dgpu to work)
alias record="gpu-screen-recorder -w screen -c mp4 -f 60 -a "$(pactl get-default-sink).monitor" -q high -o ~/Videos/now-recorded.mp4"

# functions

# make dir and then cd into it
mkcd () { mkdir -p -- "$1" && cd -P -- "$1" }

# git zip
alias gitzip="git archive HEAD -o ${PWD##*/}.zip"

### archived

# some programming thingy
# alias mdb="sudo service mongodb"
# alias lamppstart="sudo /opt/lampp/lampp start"
# alias lamppst="sudo /opt/lampp/lampp status"
# alias lamppstop="sudo /opt/lampp/lampp stop"
# alias lampprestart="sudo /opt/lampp/lampp restart"
# alias mysql="sudo /opt/lampp/bin/mysql -u root -p"
alias sail='[ -f sail ] && sh sail || sh vendor/bin/sail'
alias emulator='$ANDROID_HOME/emulator/emulator'

# fun stuff
alias chat="sgpt"
alias minecraft="prime-run gamemoderun java -jar $HOME/Documents/Minecraft.jar"
