#!/usr/bin/env bash

# initial install
# sudo pacman -Syyuu zsh neovim bat base-devel pulseaudio pamixer lxappearance brightnessctl ranger redshift flameshot alsa-utils alsa-plugins alsa-lib lxrandr-gtk3 dunst xsel unzip unrar libnotify rofi dmenu tmux

# switch to zsh
chsh -s $(which zsh)

# install paru (aur helper)
git clone https://aur.archlinux.org/paru.git && cd paru
makepkg -si
cd .. && rm -rf paru

paru auto-cpufreq

# install tmux plugin manager
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# javascript
# install volta
curl https://get.volta.sh | bash -s -- --skip-setup

# install Node
volta install node@latest

# enable fstrim.timer
systemctl enable fstrim.timer --now

# afterthought
clear
printf '========== The installation is done ==========\n'
printf "\n - You should change the .gitconfig by your own"
printf "\n - Please quit the terminal by typing 'exit'"
