#!/usr/bin/env bash

# initial install
sudo pacman -Syyuu zsh neovim bat base-devel pulseaudio pamixer lxappearance brightnessctl ranger redshift flameshot alsa-utils alsa-plugins alsa-lib lxrandr-gtk3

# install antibody 
curl -sfL git.io/antibody | sudo sh -s - -b /usr/local/bin
antibody bundle < ~/.dotfiles/dots/zsh_plugins

# install paru (aur helper)
# git clone https://aur.archlinux.org/paru.git && cd paru
# makepkg -si
# cd .. && rm -rf paru

# paru polybar
# paru auto-cpufreq

# install tmux plugin manager
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# javascript
# install volta
curl https://get.volta.sh | bash -s -- --skip-setup

# install Node
volta install node@latest

# ruby
# install rbenv
#git clone https://github.com/rbenv/rbenv.git ~/.rbenv

# intall ruby build plugin
#mkdir -p "$(rbenv root)"/plugins
#git clone https://github.com/rbenv/ruby-build.git "$(rbenv root)"/plugins/ruby-build

# install ruby
#rbenv install 2.7.2 --verbose
#rbenv global 2.7.2

# afterthought
clear
printf '========== The installation is done ==========\n'
printf "\n - Please quit the terminal by typing 'exit'"
