#!/usr/bin/env bash

# initial install
sudo apt install zsh \
    git \
    zip \
    unzip \
    build-essential \
    vim \
    neovim \
    tmux \

# change shell to zsh
printf "\nChange shell to zsh\n";
chsh -s $(which zsh)
echo 

# install antibody 
curl -sfL git.io/antibody | sudo sh -s - -b /usr/local/bin
antibody bundle < ~/dotfiles/.zsh_plugins

# install nvim plugin manager
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# install tmux plugin manager
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# install git
if [ ! -f "/home/$(whoami)/.ssh/id_ed25519.pub" ]; then
  read -p 'Input your email: ' email
  ssh-keygen -t ed25519 -C "${email}"
fi

# install volta
curl https://get.volta.sh | bash -s -- --skip-setup

# install Node
volta install node@latest

# install rbenv
git clone https://github.com/rbenv/rbenv.git ~/.rbenv

# intall ruby build plugin
mkdir -p "$(rbenv root)"/plugins
git clone https://github.com/rbenv/ruby-build.git "$(rbenv root)"/plugins/ruby-build

# install ruby
rbenv install 2.7.2 --verbose
rbenv global 2.7.2

# afterthought
clear
printf '========== The installation is done ==========\n'
printf "\n - Please quit the terminal by typing 'exit' after the installation"
# output public key
printf "\n - This is your SSH key: \n\n"
cat ~/.ssh/id_ed25519.pub
printf "\n - Copy your key to Github (CTRL + Mouse1): https://github.com/settings/ssh/new\n"
