#!/bin/sh

while read file
do
        case "$1" in
        "C-d")
                mv "$file" ~/.trash ;;
        "C-r")
                convert -rotate 90 "$file" "$file" ;;
        "C-c")
                echo -n "$file" | xclip -selection clipboard ;;
        "C-w")
                $HOME/.dotfiles/scripts/wal-sync.sh $file ;;
        esac
done
